package entity;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.xy
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String xy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.kxh
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String kxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.kch
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String kch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.kcm
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String kcm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.xf
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String xf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.xs
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String xs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.zxs
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String zxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.rkjs1
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String rkjs1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.rkjs2
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String rkjs2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.sksj
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String sksj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.skzc
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String skzc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.skdd
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String skdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.bj
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String bj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.nj
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String nj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.rs
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String rs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.xq
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    private String xq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.xy
     *
     * @return the value of course.xy
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getXy() {
        return xy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.xy
     *
     * @param xy the value for course.xy
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setXy(String xy) {
        this.xy = xy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.kxh
     *
     * @return the value of course.kxh
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getKxh() {
        return kxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.kxh
     *
     * @param kxh the value for course.kxh
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setKxh(String kxh) {
        this.kxh = kxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.kch
     *
     * @return the value of course.kch
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getKch() {
        return kch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.kch
     *
     * @param kch the value for course.kch
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setKch(String kch) {
        this.kch = kch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.kcm
     *
     * @return the value of course.kcm
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getKcm() {
        return kcm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.kcm
     *
     * @param kcm the value for course.kcm
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setKcm(String kcm) {
        this.kcm = kcm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.xf
     *
     * @return the value of course.xf
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getXf() {
        return xf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.xf
     *
     * @param xf the value for course.xf
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setXf(String xf) {
        this.xf = xf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.xs
     *
     * @return the value of course.xs
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getXs() {
        return xs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.xs
     *
     * @param xs the value for course.xs
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setXs(String xs) {
        this.xs = xs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.zxs
     *
     * @return the value of course.zxs
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getZxs() {
        return zxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.zxs
     *
     * @param zxs the value for course.zxs
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setZxs(String zxs) {
        this.zxs = zxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.rkjs1
     *
     * @return the value of course.rkjs1
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getRkjs1() {
        return rkjs1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.rkjs1
     *
     * @param rkjs1 the value for course.rkjs1
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setRkjs1(String rkjs1) {
        this.rkjs1 = rkjs1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.rkjs2
     *
     * @return the value of course.rkjs2
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getRkjs2() {
        return rkjs2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.rkjs2
     *
     * @param rkjs2 the value for course.rkjs2
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setRkjs2(String rkjs2) {
        this.rkjs2 = rkjs2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.sksj
     *
     * @return the value of course.sksj
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getSksj() {
        return sksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.sksj
     *
     * @param sksj the value for course.sksj
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setSksj(String sksj) {
        this.sksj = sksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.skzc
     *
     * @return the value of course.skzc
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getSkzc() {
        return skzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.skzc
     *
     * @param skzc the value for course.skzc
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setSkzc(String skzc) {
        this.skzc = skzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.skdd
     *
     * @return the value of course.skdd
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getSkdd() {
        return skdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.skdd
     *
     * @param skdd the value for course.skdd
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setSkdd(String skdd) {
        this.skdd = skdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.bj
     *
     * @return the value of course.bj
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getBj() {
        return bj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.bj
     *
     * @param bj the value for course.bj
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setBj(String bj) {
        this.bj = bj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.nj
     *
     * @return the value of course.nj
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getNj() {
        return nj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.nj
     *
     * @param nj the value for course.nj
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setNj(String nj) {
        this.nj = nj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.rs
     *
     * @return the value of course.rs
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getRs() {
        return rs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.rs
     *
     * @param rs the value for course.rs
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setRs(String rs) {
        this.rs = rs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.xq
     *
     * @return the value of course.xq
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public String getXq() {
        return xq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.xq
     *
     * @param xq the value for course.xq
     *
     * @mbggenerated Tue Nov 05 14:35:52 CST 2019
     */
    public void setXq(String xq) {
        this.xq = xq;
    }
}